
#Use when service and agent are running on docker
version: '3'
services:
  notes:
    container_name: notes
    restart: always
    build: 
      context: ../
      dockerfile: dockerfile.notes
    ports:
      - 8080:8080
    labels:
      - com.datadoghq.tags.service=notes
      - com.datadoghq.tags.env=dev
      - com.datadoghq.tags.version=0.0.1
    environment:
      - DD_SERVICE=notes
      - DD_ENV=dev
      - DD_VERSION=0.0.1
      - DD_AGENT_HOST=datadog-agent
      - CALENDAR_HOST=calendar
      - ENV=dev
      - SERVICE=notes
      - VERSION=0.0.1
    depends_on:
      calendar:
        condition: service_started
      datadog-agent:
        condition: service_healthy

  calendar:
    container_name: calendar
    restart: always
    build: 
      context: ../
      dockerfile: dockerfile.calendar
    labels:
       - com.datadoghq.tags.service=calendar
       - com.datadoghq.tags.env=dev
       - com.datadoghq.tags.version=0.0.1
    environment:
       - DD_SERVICE=calendar
       - DD_ENV=dev
       - DD_VERSION=0.0.1
       - DD_AGENT_HOST=datadog-agent
    ports:
      - 9090:9090
    depends_on:
      datadog-agent:
        condition: service_healthy

      
  datadog-agent:
    container_name: datadog-agent
    image: "gcr.io/datadoghq/agent:latest"
    pid: host
    environment:
      - DD_API_KEY=<DD_API_KEY_HERE>
      - DD_SITE=us5.datadoghq.com
      - DD_APM_ENABLED=true
      - DD_APM_NON_LOCAL_TRAFFIC=true
      - DD_DOGSTATSD_NON_LOCAL_TRAFFIC=true
      - DD_LOGS_ENABLED=true
      - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true
      - DD_CONTAINER_EXCLUDE=image:datadoghq/agent:*
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /opt/datadog-agent/run:/opt/datadog-agent/run:rw
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8126/info"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
